export const gstStates = {
  35: 'Andaman and Nicobar Islands',
  37: 'Andhra Pradesh',
  12: 'Arunachal Pradesh',
  18: 'Assam',
  10: 'Bihar',
  4: 'Chandigarh',
  22: 'Chhattisgarh',
  26: 'Dadra and Nagar Haveli',
  25: 'Daman and Diu',
  7: 'Delhi',
  30: 'Goa',
  24: 'Gujarat',
  6: 'Haryana',
  2: 'Himachal Pradesh',
  1: 'Jammu and Kashmir',
  20: 'Jharkhand',
  29: 'Karnataka',
  32: 'Kerala',
  38: 'Ladakh',
  31: 'Lakshadweep',
  23: 'Madhya Pradesh',
  27: 'Maharashtra',
  14: 'Manipur',
  17: 'Meghalaya',
  15: 'Mizoram',
  13: 'Nagaland',
  21: 'Odisha',
  97: 'Other Territory',
  34: 'Puducherry',
  3: 'Punjab',
  8: 'Rajasthan',
  11: 'Sikkim',
  33: 'Tamil Nadu',
  36: 'Telangana',
  16: 'Tripura',
  9: 'Uttar Pradesh',
  5: 'Uttarakhand',
  19: 'West Bengal'
}
